- name: Download wordpress
  ansible.builtin.get_url:
    url: https://ja.wordpress.org/latest-ja.zip
    dest: /tmp/
  tags:
    - install-wordpress

- name: Unarchive wordpress
  ansible.builtin.unarchive:
    src: /tmp/wordpress-7.0-ja.zip
    dest: /tmp/
    remote_src: true
  tags:
    - install-wordpress

- name: Move wordpress to document root
  ansible.builtin.copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: true
    owner: apache
    group: apache
  tags:
    - install-wordpress
